package util;

/**
 * ======== Multi-purpose generator ======== <br>
 * Automatically create a generator, given a class with default constructor. The
 * object to be generated by this class must have public, not just package
 * access (because this generator is in a separate package) and has a default
 * constructor.
 * 
 * @author pirent
 *
 */
public class BasicGenerator<T> implements Generator<T> {

	private Class<T> type;

	public BasicGenerator(Class<T> type) {
		super();
		this.type = type;
	}

	@Override
	public T next() {
		try {
			return type.newInstance();
		}
		catch (InstantiationException | IllegalAccessException e) {
			throw new RuntimeException(e);
		}
	}

	public static <T> Generator<T> create(Class<T> type) {
		return new BasicGenerator<T>(type);
	}
}
